- name: Update apt repository
  apt: 
    update_cache=yes 
    force_apt_get=yes 
    cache_valid_time=3600
  tags: docker

- name: Install packages
  apt: 
    name: 
      - ca-certificates
      - curl
      - gnupg
    state: present
  tags: docker

- name: Create directory for keyrings
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  tags: docker
    
- name: Download docker GPG key
  shell: |
    curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    sudo chmod a+r /etc/apt/keyrings/docker.gpg
  args:
    executable: /bin/bash
  tags: docker

- name: Add docker repository to apt sources
  blockinfile:
    path: /etc/apt/sources.list.d/docker.list
    block: |
      deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable
    create: yes
  tags: docker

- name: Update apt repository
  apt: 
    update_cache=yes 
    force_apt_get=yes 
    cache_valid_time=3600
  tags: docker

- name: Install docker packages
  apt: 
    name: 
      - docker.io
      - docker-compose
    state: present
  tags: docker

- name: Create docker folder
  file: 
    name: ~/docker-compose
    state: directory
  tags: docker