---
- hosts: raspberrypi
  become : yes
  vars_files:
    - vault.yml
  tasks: 
    - name: Check connection
      action: ping

    - name: Import update playbook
      include_tasks: "./tasks/update.yml"
      tags: update
      when: "'update' in ansible_run_tags"

    - name: Import disk status playbook
      include_tasks: "./tasks/disk_status.yml"
      tags: disk_status
      when: "'disk_status' in ansible_run_tags"
    
    - name: Import docker install playbook
      include_tasks: "./tasks/docker.yml"
      tags: docker
      when: "'docker' in ansible_run_tags"

    - name: Import PiHole install playbook
      include_tasks: "./tasks/pihole.yml"
      tags: pihole
      when: "'pihole' in ansible_run_tags"

    - name: Import InfluxDB install playbook
      include_tasks: "./tasks/influxdb.yml"
      tags: influxdb
      when: "'influxdb' in ansible_run_tags"


